支持下载文件时保留文件名
amakerlife/tchMaterial-downloader pull request #1
Opened 2024-07-30 07:02 UTC by kakasearch

通过GM_download下载可以指定文件名，另外给用户添加了一个即将开始下载的提示

2024-07-30 11:48 UTC, amakerlife commented on main.user.js
> +            document.title = `[Redirecting] ${originalTitle}`;
这样的话标题就不用改了吧

2024-07-30 11:52 UTC, amakerlife requested changes

2024-07-30 11:52 UTC, amakerlife commented on main.user.js
> +            new ElegantAlertBox("正在解析，即将开始下载")
应该要留一个直接在浏览器中打开 pdf 链接的按钮之类的让用户选择？这里用 sweetalert 之类的是不是可以，或者同时进行下载和新标签页跳 pdf 链接？

2024-07-30 13:33 UTC, kakasearch commented on main.user.js
> +            document.title = `[Redirecting] ${originalTitle}`;
是的，标题不需要修改

2024-07-30 13:47 UTC, kakasearch commented on main.user.js
> +            new ElegantAlertBox("正在解析，即将开始下载")
用户使用脚本的目的就是为了下载，不过确实可以给用户一个按钮来选择是否下载，每次打开页面就下载有些打扰用户和浪费服务器资源。
ElegantAlert和 sweetalert 功能类似，都是为了给用户一个简单的提示信息

2024-07-31 02:46 UTC, amakerlife commented on main.user.js
> +            new ElegantAlertBox("正在解析，即将开始下载")
> 用户使用脚本的目的就是为了下载，不过确实可以给用户一个按钮来选择是否下载，每次打开页面就下载有些打扰用户和浪费服务器资源。 ElegantAlert和 sweetalert 功能类似，都是为了给用户一个简单的提示信息

似乎 ElegantAlert 不能让用户选择？我觉得还是弹一个 alert 来询问要下载还是直接在浏览器中看比较好。我有时候就只是打开看一眼目录或某一小部分内容，不需要再下载下来看完手动删。

2024-07-31 02:47 UTC, amakerlife commented on main.user.js
> +            new ElegantAlertBox("正在解析，即将开始下载")
你改改改完 commit 过来我 merge？顺手也把标题那个删了

2024-07-31 02:48 UTC, kakasearch commented on main.user.js
> +            new ElegantAlertBox("正在解析，即将开始下载")
每次打开页面都弹出来alert感觉有些打扰用户，要不做个悬浮的按钮，用户想下载的时候点一下就好

2024-07-31 03:34 UTC, amakerlife commented on main.user.js
> +            new ElegantAlertBox("正在解析，即将开始下载")
> 每次打开页面都弹出来alert感觉有些打扰用户，要不做个悬浮的按钮，用户想下载的时候点一下就好

可以你觉得怎么好就怎么写吧，我最近需求也不大了，更不知道怎么搞🤣

2024-07-31 03:35 UTC, kakasearch commented on main.user.js
> +            new ElegantAlertBox("正在解析，即将开始下载")
哈哈哈，ok

2024-08-02 15:43 UTC, kakasearch commented
已经删除了修改网页标题的代码，同时增加了下载按钮。用户现在打开页面后不会立刻下载，只有用户点击菜单栏的【下载电子课本】按钮时才会执行下载，如下图所示
![下载课本](https://github.com/user-attachments/assets/0a910a2d-1e4b-4bb8-a725-658707b15068)

2024-08-03 12:20 UTC, amakerlife commented
> 已经删除了修改网页标题的代码，同时增加了下载按钮。用户现在打开页面后不会立刻下载，只有用户点击菜单栏的【下载电子课本】按钮时才会执行下载，如下图所示 ![下载课本](https://private-user-images.githubusercontent.com/62104649/354649814-0a910a2d-1e4b-4bb8-a725-658707b15068.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2ODc5MTksIm5iZiI6MTcyMjY4NzYxOSwicGF0aCI6Ii82MjEwNDY0OS8zNTQ2NDk4MTQtMGE5MTBhMmQtMWU0Yi00YmI4LWE3MjUtNjU4NzA3YjE1MDY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDEyMjAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MzBmNDY2MDUwNjljMTk0MTYwNjM3Zjk0N2RlNTlkZWEzODg1ZWI2YWU2YTA0NmE0Y2U0ZDM1N2ZmOTk0NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IB_swFvEgV9a3YBT_DAR15GMbKZ_E0iJ5jEPxKeXlRY) [ ![下载课本](https://private-user-images.githubusercontent.com/62104649/354649814-0a910a2d-1e4b-4bb8-a725-658707b15068.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2ODc5MTksIm5iZiI6MTcyMjY4NzYxOSwicGF0aCI6Ii82MjEwNDY0OS8zNTQ2NDk4MTQtMGE5MTBhMmQtMWU0Yi00YmI4LWE3MjUtNjU4NzA3YjE1MDY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDEyMjAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MzBmNDY2MDUwNjljMTk0MTYwNjM3Zjk0N2RlNTlkZWEzODg1ZWI2YWU2YTA0NmE0Y2U0ZDM1N2ZmOTk0NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IB_swFvEgV9a3YBT_DAR15GMbKZ_E0iJ5jEPxKeXlRY) ](https://private-user-images.githubusercontent.com/62104649/354649814-0a910a2d-1e4b-4bb8-a725-658707b15068.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2ODc5MTksIm5iZiI6MTcyMjY4NzYxOSwicGF0aCI6Ii82MjEwNDY0OS8zNTQ2NDk4MTQtMGE5MTBhMmQtMWU0Yi00YmI4LWE3MjUtNjU4NzA3YjE1MDY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDEyMjAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MzBmNDY2MDUwNjljMTk0MTYwNjM3Zjk0N2RlNTlkZWEzODg1ZWI2YWU2YTA0NmE0Y2U0ZDM1N2ZmOTk0NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IB_swFvEgV9a3YBT_DAR15GMbKZ_E0iJ5jEPxKeXlRY) [ ](https://private-user-images.githubusercontent.com/62104649/354649814-0a910a2d-1e4b-4bb8-a725-658707b15068.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2ODc5MTksIm5iZiI6MTcyMjY4NzYxOSwicGF0aCI6Ii82MjEwNDY0OS8zNTQ2NDk4MTQtMGE5MTBhMmQtMWU0Yi00YmI4LWE3MjUtNjU4NzA3YjE1MDY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDEyMjAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MzBmNDY2MDUwNjljMTk0MTYwNjM3Zjk0N2RlNTlkZWEzODg1ZWI2YWU2YTA0NmE0Y2U0ZDM1N2ZmOTk0NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IB_swFvEgV9a3YBT_DAR15GMbKZ_E0iJ5jEPxKeXlRY)

写了一个 #2，这样可能更好？

2024-08-03 12:21 UTC, amakerlife commented
我先把这个 merge 了

2024-08-03 12:22 UTC, amakerlife approved these changes

2024-08-03 12:23 UTC, merged